# Generated by Django 6.1.1 on 2026-09-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='new email address'),
        ),
    ]
