# Generated by Django 6.1.1 on 2026-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationotp_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False, help_text='Designates whether this user authenticated with Google OAuth.', verbose_name='google account'),
        ),
    ]
